### ISSUE TITLE
Connecting to server, hangs in `read_expected`, Python >=3.10?

### ISSUE THREAD

**Issue by albertz** [albertz/python-preloaded#1]
Python 3.10 and 3.11 seems to hang? On Ubuntu 22.04:
```
zeyer@indigo ~/c/python-preloaded (main)> python3.11 python-demo.bin
Existing socket, connected
Open new PTY
Send PTY fd to server
Wait for server to be ready
^CTraceback (most recent call last):
  File "/u/zeyer/code/python-preloaded/python-demo.bin", line 11, in <module>
    startup_via_fork_server(modules=['os'])
  File "/u/zeyer/code/python-preloaded/preloaded/startup.py", line 63, in startup_via_fork_server
    fork_server.child_main(sock=sock)
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 27, in child_main
    _io.read_expected(p2c_r, b"ok")
  File "/u/zeyer/code/python-preloaded/preloaded/_io.py", line 49, in read_expected
    res = f.read(len(expected))
          ^^^^^^^^^^^^^^^^^^^^^
  File "/u/zeyer/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

**Comment by albertz** [comment]
It seems the receiving of the FD somehow fails. I see in the stderr from the server:
```
Handle child: ['python-demo.bin']
Traceback (most recent call last):
  File "/u/zeyer/code/python-preloaded/python-demo.bin", line 11, in <module>
    startup_via_fork_server(modules=['os'])
  File "/u/zeyer/code/python-preloaded/preloaded/startup.py", line 78, in startup_via_fork_server
    fork_server.server_main(
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 96, in server_main
    server_handle_child(conn)
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 120, in server_handle_child
    msg, (slave_fd,) = _recv_fds(conn, msglen=3, maxfds=1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 157, in _recv_fds
    assert msg and ancdata, f"recvmsg failed, got msg {msg!r}, ancdata {ancdata!r}, flags {flags!r}, addr {addr!r}"
AssertionError: recvmsg failed, got msg b'', ancdata [], flags 0, addr None
```
I wonder how that can be. The socket should be in blocking mode. The socket should still be open. How can it be that it returns an empty msg? How can it be that this changed in a recent Python version?

**Comment by albertz** [comment]
Maybe the FD or socket is actually closed somewhere? Maybe due to forking? Maybe some `set_inheritable` related logic?

**Comment by albertz** [comment]
Oh, I realize (via `trace -e trace=file,socket -f -T python3.11 python-demo.bin` on the server), it only closes it once the child gets interrupted via Ctrl+C. The child before just hangs after "Wait for server to be ready".

**Comment by albertz** [comment]
So the child hangs here:
```
Existing socket, connected
Python-preloaded fork-server child main, pid 282945
Open new PTY
Send PTY fd to server
Wait for server to be ready
Current thread 0x00007f8dcf5f2c40 (most recent call first):
  File "/u/zeyer/.linuxbrew/Cellar/python@3.11/3.11.2_1/lib/python3.11/socket.py", line 706 in readinto
  File "/u/zeyer/code/python-preloaded/preloaded/_io.py", line 49 in read_expected
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 28 in child_main
  File "/u/zeyer/code/python-preloaded/preloaded/startup.py", line 67 in startup_via_fork_server
  File "/u/zeyer/code/python-preloaded/python-demo.bin", line 11 in <module>
```
And the server hangs here:
```
Handle child: ['python-demo.bin']
Current thread 0x00007fc4b7c92c40 (most recent call first):
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 157 in _recv_fds
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 122 in server_handle_child
  File "/u/zeyer/code/python-preloaded/preloaded/fork_server.py", line 98 in server_main
  File "/u/zeyer/code/python-preloaded/preloaded/startup.py", line 82 in startup_via_fork_server
  File "/u/zeyer/code/python-preloaded/python-demo.bin", line 11 in <module>
```
Does the child needs some flush after the `_send_fds`?

**Comment by albertz** [comment]
When you look at that fixing commit (5266aaa71a4e11e526f630e869d9e9d83f28a3d0), the actual change is that I added `buffering=0` for the `sock.makefile` calls. I assume this buffering caused problems when the socket was also used more directly via `sendmsg`/`recvmsg`. We anyway don't need, actually even don't want the buffering there.
